team_size: 5 # default size of a team within the league
league_play_time_mins: 60 # how long is a play against one opponent running in minutes
league_runtime_hours: 48 # hofcw long is the hole league running in hours