team_size: 5 # default size of a team within the league
league_play_time_mins: 120 # how long is a play against one opponent running in minutes
league_runtime_hours: 24 # how long is the hole league running in hours
n_league_evaluation_episodes: 100
show_exp_parameters: True

buffer_cpu_only: False
mac: "ensemble"
headless_controls: False
use_cuda: True
use_tensorboard: True

matchmaking: "random"