team_size: 5 # default size of a team within the league
league_play_time_mins: 0.05 # how long is a play against one opponent running in minutes
league_runtime_hours: 0.0017 # how long is the hole league running in hours
n_league_evaluation_episodes: 1
show_exp_parameters: True

env_args:
  record: False
  fps: 60

mac: "basic"
headless_controls: "False"
use_cuda: "True"
use_tensorboard: "True"

matchmaking: "random"