env: ma
play_mode: normal

env_args:
  headless: True
  record: False
  fps: 30
  draw_grid: False
  infos: True
  global_reward: True
  grid_size: 10
  match_build_plan: medium

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
