env: ma
play_mode: normal

env_args:
  headless: True
  record: False
  fps: 30
  draw_grid: False
  infos: False
  global_reward: True
  grid_size: 20
  match_build_plan: small
  ai: basic
  stochastic_spawns: False
  attack_ranges_only: False

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
