env: ma
self_play: False
league_play: False

env_args:
  headless: True
  record: False
  fps: 30
  draw_grid: False
  infos: True
  seed: null
  global_reward: True

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
